In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.21.0'

In [3]:
data=pd.read_csv(r'C:/Users/aarun/Agentic AI/DeepLearning/Churn_Modelling.csv')

In [4]:
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [5]:
X = data.iloc[:, 3:-1].values
y = data.iloc[:, -1].values

In [6]:
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [7]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]],
      shape=(10000, 10), dtype=object)

In [8]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [9]:
le=LabelEncoder()
X[:,2]=le.fit_transform(X[:,2])

In [10]:
X

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]],
      shape=(10000, 10), dtype=object)

In [11]:
from sklearn.compose import ColumnTransformer
ct=ColumnTransformer([('encoder',OneHotEncoder(),[1])],remainder='passthrough')
X=np.array(ct.fit_transform(X))

In [12]:
X

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]],
      shape=(10000, 12), dtype=object)

In [13]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X=sc.fit_transform(X)

In [14]:
X

array([[ 0.99720391, -0.57873591, -0.57380915, ...,  0.64609167,
         0.97024255,  0.02188649],
       [-1.00280393, -0.57873591,  1.74273971, ..., -1.54776799,
         0.97024255,  0.21653375],
       [ 0.99720391, -0.57873591, -0.57380915, ...,  0.64609167,
        -1.03067011,  0.2406869 ],
       ...,
       [ 0.99720391, -0.57873591, -0.57380915, ..., -1.54776799,
         0.97024255, -1.00864308],
       [-1.00280393,  1.72790383, -0.57380915, ...,  0.64609167,
        -1.03067011, -0.12523071],
       [ 0.99720391, -0.57873591, -0.57380915, ...,  0.64609167,
        -1.03067011, -1.07636976]], shape=(10000, 12))

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [16]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(8000, 12)
(2000, 12)
(8000,)
(2000,)

In [17]:
#ANN MODEL BUILDING ARCHITECTURE

In [ ]:
ann=tf.keras.models.Sequential()
#eslabilish layers in the ANN

In [19]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [20]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [21]:
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [22]:
ann.fit(X_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 963us/step - accuracy: 0.7514 - loss: 0.5400
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 992us/step - accuracy: 0.7959 - loss: 0.4597
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 895us/step - accuracy: 0.7970 - loss: 0.4360
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 895us/step - accuracy: 0.8034 - loss: 0.4257
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 900us/step - accuracy: 0.8112 - loss: 0.4191
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 949us/step - accuracy: 0.8174 - loss: 0.4129
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 870us/step - accuracy: 0.8231 - loss: 0.4067
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 975us/step - accuracy: 0.8257 - loss: 0.4008
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 859us/step - accuracy: 0.8265 - loss: 0.3959
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 870us/step - accuracy: 0.8288 - loss: 0.3922
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 915us/step - accuracy: 0.8291 - loss: 0.3888
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 864us/step - accuracy: 0.8317 - loss: 0.3861
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 840us/step - accuracy: 0.8304 - loss: 0.3841
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 881us/step - accuracy: 0.8311 - loss: 0.3823
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 971us/step - accuracy: 0.8328 - loss: 0.3804
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 833us/step - accuracy: 0.8388 - loss: 0.3787
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 902us/step - accuracy: 0.8400 - loss: 0.3774
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 895us/step - accuracy: 0.8403 - loss: 0.3760
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 836us/step - accuracy: 0.8393 - loss: 0.3748
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 921us/step - accuracy: 0.8409 - loss: 0.3735
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - accuracy: 0.8434 - loss: 0.3725
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 843us/step - accuracy: 0.8429 - loss: 0.3715
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 890us/step - accuracy: 0.8434 - loss: 0.3705
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 897us/step - accuracy: 0.8441 - loss: 0.3696
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 846us/step - accuracy: 0.8426 - loss: 0.3688
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 905us/step - accuracy: 0.8455 - loss: 0.3679
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 875us/step - accuracy: 0.8462 - loss: 0.3671
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 837us/step - accuracy: 0.8465 - loss: 0.3665
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 879us/step - accuracy: 0.8465 - loss: 0.3660
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 852us/step - accuracy: 0.8468 - loss: 0.3654
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 837us/step - accuracy: 0.8478 - loss: 0.3645
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 883us/step - accuracy: 0.8495 - loss: 0.3644
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 867us/step - accuracy: 0.8487 - loss: 0.3634
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 874us/step - accuracy: 0.8481 - loss: 0.3631
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 856us/step - accuracy: 0.8487 - loss: 0.3626
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 889us/step - accuracy: 0.8495 - loss: 0.3621
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 869us/step - accuracy: 0.8495 - loss: 0.3618
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 896us/step - accuracy: 0.8512 - loss: 0.3615
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 866us/step - accuracy: 0.8501 - loss: 0.3611
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 965us/step - accuracy: 0.8522 - loss: 0.3604
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 901us/step - accuracy: 0.8520 - loss: 0.3599
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 903us/step - accuracy: 0.8504 - loss: 0.3598
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 902us/step - accuracy: 0.8534 - loss: 0.3590
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 881us/step - accuracy: 0.8529 - loss: 0.3588
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 878us/step - accuracy: 0.8545 - loss: 0.3582
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 887us/step - accuracy: 0.8545 - loss: 0.3578
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 887us/step - accuracy: 0.8546 - loss: 0.3576
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 855us/step - accuracy: 0.8522 - loss: 0.3570
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 887us/step - accuracy: 0.8554 - loss: 0.3567
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 874us/step - accuracy: 0.8550 - loss: 0.3565
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 881us/step - accuracy: 0.8555 - loss: 0.3557
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 912us/step - accuracy: 0.8556 - loss: 0.3558
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 851us/step - accuracy: 0.8555 - loss: 0.3555
Epoch 54/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 858us/step - accuracy: 0.8553 - loss: 0.3550
Epoch 55/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 860us/step - accuracy: 0.8570 - loss: 0.3550
Epoch 56/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 868us/step - accuracy: 0.8540 - loss: 0.3541
Epoch 57/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 881us/step - accuracy: 0.8551 - loss: 0.3544
Epoch 58/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - accuracy: 0.8566 - loss: 0.3540
Epoch 59/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 864us/step - accuracy: 0.8569 - loss: 0.3540
Epoch 60/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 862us/step - accuracy: 0.8569 - loss: 0.3536
Epoch 61/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 845us/step - accuracy: 0.8574 - loss: 0.3529
Epoch 62/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 844us/step - accuracy: 0.8560 - loss: 0.3531
Epoch 63/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 834us/step - accuracy: 0.8560 - loss: 0.3529
Epoch 64/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 851us/step - accuracy: 0.8568 - loss: 0.3525
Epoch 65/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 873us/step - accuracy: 0.8569 - loss: 0.3521
Epoch 66/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 849us/step - accuracy: 0.8570 - loss: 0.3523
Epoch 67/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - accuracy: 0.8576 - loss: 0.3521
Epoch 68/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 814us/step - accuracy: 0.8562 - loss: 0.3522
Epoch 69/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 857us/step - accuracy: 0.8595 - loss: 0.3518
Epoch 70/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 828us/step - accuracy: 0.8584 - loss: 0.3515
Epoch 71/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 865us/step - accuracy: 0.8571 - loss: 0.3513
Epoch 72/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 840us/step - accuracy: 0.8565 - loss: 0.3509
Epoch 73/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 826us/step - accuracy: 0.8579 - loss: 0.3515
Epoch 74/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 841us/step - accuracy: 0.8571 - loss: 0.3505
Epoch 75/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 847us/step - accuracy: 0.8594 - loss: 0.3507
Epoch 76/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 836us/step - accuracy: 0.8596 - loss: 0.3505
Epoch 77/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 879us/step - accuracy: 0.8594 - loss: 0.3505
Epoch 78/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 875us/step - accuracy: 0.8591 - loss: 0.3502
Epoch 79/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 827us/step - accuracy: 0.8591 - loss: 0.3502
Epoch 80/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 861us/step - accuracy: 0.8575 - loss: 0.3500
Epoch 81/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 838us/step - accuracy: 0.8586 - loss: 0.3500
Epoch 82/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 887us/step - accuracy: 0.8589 - loss: 0.3500
Epoch 83/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 914us/step - accuracy: 0.8579 - loss: 0.3498
Epoch 84/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 917us/step - accuracy: 0.8581 - loss: 0.3498
Epoch 85/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 915us/step - accuracy: 0.8601 - loss: 0.3494
Epoch 86/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 924us/step - accuracy: 0.8589 - loss: 0.3492
Epoch 87/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 960us/step - accuracy: 0.8600 - loss: 0.3491
Epoch 88/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 882us/step - accuracy: 0.8595 - loss: 0.3490
Epoch 89/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 899us/step - accuracy: 0.8589 - loss: 0.3492
Epoch 90/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 861us/step - accuracy: 0.8589 - loss: 0.3491
Epoch 91/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 834us/step - accuracy: 0.8595 - loss: 0.3489
Epoch 92/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 891us/step - accuracy: 0.8593 - loss: 0.3489
Epoch 93/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 826us/step - accuracy: 0.8601 - loss: 0.3487
Epoch 94/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 889us/step - accuracy: 0.8610 - loss: 0.3485
Epoch 95/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 874us/step - accuracy: 0.8589 - loss: 0.3484
Epoch 96/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1000us/step - accuracy: 0.8606 - loss: 0.3485
Epoch 97/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 883us/step - accuracy: 0.8575 - loss: 0.3484
Epoch 98/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 898us/step - accuracy: 0.8591 - loss: 0.3484
Epoch 99/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 905us/step - accuracy: 0.8599 - loss: 0.3481
Epoch 100/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 948us/step - accuracy: 0.8615 - loss: 0.3481

In [23]:
y_pred=ann.predict(X_test)
y_pred=(y_pred>0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]